In [1]:
import numpy as np

In [2]:
np.array([[1,2],[3,4]])@np.array([[1],[2]])

array([[ 5],
       [11]])

In [7]:
# 선형조합
1*np.array([[1],[3]])+2*np.array([[2],[4]])

array([[ 5],
       [11]])

In [3]:
np.array([[1,2,3],[4,5,6]])@np.array([[2],[3],[4]])


array([[20],
       [47]])

In [9]:
#부분행렬
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [10]:
a@b

array([[19, 22],
       [43, 50]])

In [21]:
# 1. a를 행벡터로 쪼개기
a

array([[1, 2],
       [3, 4]])

In [28]:
np.array(([2],[4])) @np.array([[7,8]]) 

array([[14, 16],
       [28, 32]])

In [ ]:
# 2.