In [1]:
import numpy as np

In [2]:
np.array([[1,2],[3,4]])@np.array([[1],[2]])

array([[ 5],
       [11]])

In [7]:
# 선형조합
1*np.array([[1],[3]])+2*np.array([[2],[4]])

array([[ 5],
       [11]])

In [3]:
np.array([[1,2,3],[4,5,6]])@np.array([[2],[3],[4]])


array([[20],
       [47]])