# 전처리

### 1. 레이블 인코딩

In [2]:
# 분류문제의 target에만 적용해야 합니다~!~!
from sklearn.preprocessing import LabelEncoder

items = ["청바지", "치마", "청바지", "원피스", "청바지", "치마", "치마", "청바지", "원피스"]

lbl_encoder = LabelEncoder()
lbl_encoder.fit(items)

LabelEncoder()

In [3]:
# .transform : 문자열 items를 숫자로 인코딩 
labels= lbl_encoder.transform(items)
labels

array([1, 2, 1, 0, 1, 2, 2, 1, 0])

In [6]:
# .inverse_transform : 숫자를 다시 문자열로 돌려주는 과정을 디코딩(Decode)
lbl_encoder.inverse_transform(labels)

array(['청바지', '치마', '청바지', '원피스', '청바지', '치마', '치마', '청바지', '원피스'],
      dtype='<U3')

In [7]:
lbl_encoder.classes_

array(['원피스', '청바지', '치마'], dtype='<U3')

In [9]:
lbl_encoder.classes_

array(['원피스', '청바지', '치마'], dtype='<U3')

In [10]:
from sklearn.preprocessing import OneHotEncoder

ohe_encoder = OneHotEncoder() 

### One-Hot Encoding

타겟을 바꾸는 레이블 인코딩에 반해

`Feature`를 바꾸는 원핫 인코더는 행렬을 parameter로 받는다. 

Label ∈ Rⁿ

Feature ∈ |Rⁿxⁿ

In [15]:
import numpy as np

items_arr = np.array([items])

In [16]:
items_arr.ndim

2

In [23]:
items_arr

array([['청바지', '치마', '청바지', '원피스', '청바지', '치마', '치마', '청바지', '원피스']],
      dtype='<U3')

In [24]:
items_arr=items_arr.T

In [25]:
ohe_labels=ohe_encoder.fit_transform(items_arr)
ohe_labels

<9x3 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

```
<9x3 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>
```
sparse matrix : 희소행렬 
- one-hot encoding 은 기본적으로 `쓸모 없는` 데이터가 많아 메모리 소모가 많다.
- 희소행렬은 `어느 위치`에 강조값(`1`)이 존재하는지만을 보여준다.
- `compressed` 압축된

In [26]:
print(ohe_labels) 

  (0, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 1)	1.0
  (8, 0)	1.0


In [27]:
# 희소행렬의 압축을 풀어서 표현
ohe_labels.toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

# 스케일링

In [28]:
#MinMax Scaling(정규화)
import pandas as pd
movie_score = pd.DataFrame({
    "naver":[0, 2, 4, 6, 8],
    "netflix":[1, 2, 3, 4, 5]
})

movie_score

naver  netflix
0      0        1
1      2        2
2      4        3
3      6        4
4      8        5

In [30]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

In [31]:
#fit_transform : 입력과 변환을 동시에
movie_score_scaled=min_max_scaler.fit_transform(movie_score)
movie_score_scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [33]:
pd.DataFrame(movie_score_scaled,columns=["네이버","넷플릭스"])

네이버  넷플릭스
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

### StandardScaling (표준화)
- 데이터를 정리한다는 개념
- 흩트러진 데이터를 원점 기준으로 정리
- 평균을 0, 표준편차를 1로 변환